### ISSUE TITLE
Cartfile error

### ISSUE THREAD

**Issue by SergeyOleynich** [Matzo/Kamishibai#2]
Hi. Try to use cartfile for your project and receive such error.
```
*** Skipped building Kamishibai due to the error:
Dependency "Kamishibai" has no shared framework schemes for any of the platforms: iOS
```

add dependency in Cartfile
```
github "Matzo/Kamishibai"
```
in terminal use this
```
carthage update --platform iOS
```

**Comment by Matzo** [comment]
Hi. Sorry I didn't push a tag for Carthage.
Now I have fixed it.

Please confirm it.
